GET http://localhost:5296/itens
###

GET http://localhost:5296/itens/4


###

POST  http://localhost:5296/itens/
Content-Type: application/json

{
    "name": "Leite",
    "Quantities": "10",
    "ExpirationDate": "2027-07-15"
}

###

DELETE http://localhost:5296/itens/1


###

PUT   http://localhost:5296/itens/1
Content-Type:  application/json

{
    "name": "Arroz",
    "quantities": 4,
    "expirationDate": "2030-01-30"
}
