// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lista_de_comprasAPI.Data;

#nullable disable

namespace lista_de_comprasAPI.Data.Migrations
{
    [DbContext(typeof(Lista_de_comprasContext))]
    [Migration("20250618114437_CategorySeed")]
    partial class CategorySeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("lista_de_comprasAPI.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cotidiano"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sacolão"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lanche"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Higiene pessoal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Limpeza"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Proteina"
                        });
                });

            modelBuilder.Entity("lista_de_comprasAPI.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantities")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("lista_de_comprasAPI.Entities.Item", b =>
                {
                    b.HasOne("lista_de_comprasAPI.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
